import { useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { Plus, Minus } from "lucide-react";
import { Badge, Container, Section, cn } from "../ui/Primitives";

const faqs = [
  {
    q: "How does Sentinel detect a 'runaway' agent?",
    a: "AEGIS combines three signals: (1) a heuristic engine that flags identical tool calls within a sliding time window, (2) a Gemini trace judge that scores intent — 'is this agent being thorough, or stuck?' — and (3) a cost-burn rate monitor on the Vertex AI invoice. Any one of them can trigger a heal.",
  },
  {
    q: "What does Sentinel actually do to fix the agent?",
    a: "It calls the Vertex AI Agent Builder API to atomically update the agent's `instructions` field. The new instructions are generated by Gemini after analyzing the bad trace, with a hard ceiling on retries, a single-shot tool-use policy, and an explicit refusal to repeat identical queries. Every change is git-committed and reversible in one click.",
  },
  {
    q: "Will it cause downtime for my users?",
    a: "No. The rewrite is a PATCH on the agent's instructions — not a redeploy. P50 heal latency in our benchmarks is 623ms, and the change is applied in-place. Your users see a slow tool call at most, never a 5xx.",
  },
  {
    q: "Does it work with agents I already have running?",
    a: "Yes. If your agent is instrumented with OpenInference (we support `openinference-instrumentation-vertexai`, `openinference-instrumentation-google-genai`, and the standard OTLP exporters), you can point Sentinel at it without changing a line of application code.",
  },
  {
    q: "What about data privacy?",
    a: "Sentinel runs in your own VPC or our SOC 2 environment. Trace data is processed in-memory and never used to train shared models. Enterprise plans support CMEK, VPC-SC, and bring-your-own-region deployments on GCP.",
  },
  {
    q: "How is this different from an observability dashboard?",
    a: "Observability tools tell you what your agent did. AEGIS is an action layer — it actually changes your agent's behavior in response. Think of it as the difference between a security camera and a security guard. We sit on top of Arize Phoenix, we don't replace it.",
  },
];

export default function FAQ() {
  const [open, setOpen] = useState<number | null>(0);
  return (
    <Section className="py-24 md:py-32">
      <Container>
        <div className="grid grid-cols-1 gap-12 md:grid-cols-[360px_1fr]">
          <div>
            <Badge tone="cyan">FAQ</Badge>
            <h2 className="mt-4 text-3xl font-semibold tracking-tight text-white sm:text-4xl">
              Questions, answered.
            </h2>
            <p className="mt-3 text-ink-200">
              Can't find what you're looking for?{" "}
              <a href="#" className="text-arize-200 hover:text-arize-100">
                Talk to the AEGIS team →
              </a>
            </p>
          </div>
          <div className="space-y-2.5">
            {faqs.map((f, i) => {
              const isOpen = open === i;
              return (
                <div
                  key={f.q}
                  className={cn(
                    "overflow-hidden rounded-xl border bg-gradient-to-b from-ink-850/80 to-ink-900/80 transition-colors",
                    isOpen ? "border-arize-400/30" : "border-white/[0.06]"
                  )}
                >
                  <button
                    onClick={() => setOpen(isOpen ? null : i)}
                    className="flex w-full items-center justify-between gap-4 px-4 py-3.5 text-left"
                  >
                    <span className="text-[14px] font-medium text-white">{f.q}</span>
                    <span
                      className={cn(
                        "flex h-7 w-7 shrink-0 items-center justify-center rounded-md border transition-colors",
                        isOpen
                          ? "border-arize-400/30 bg-arize-500/10 text-arize-200"
                          : "border-white/[0.06] bg-white/[0.02] text-ink-200"
                      )}
                    >
                      {isOpen ? <Minus className="h-3.5 w-3.5" /> : <Plus className="h-3.5 w-3.5" />}
                    </span>
                  </button>
                  <AnimatePresence initial={false}>
                    {isOpen && (
                      <motion.div
                        initial={{ height: 0, opacity: 0 }}
                        animate={{ height: "auto", opacity: 1 }}
                        exit={{ height: 0, opacity: 0 }}
                        transition={{ duration: 0.25, ease: [0.21, 0.6, 0.32, 1] }}
                      >
                        <div className="border-t border-white/[0.04] px-4 py-3.5 text-[13.5px] leading-relaxed text-ink-200">
                          {f.a}
                        </div>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </div>
              );
            })}
          </div>
        </div>
      </Container>
    </Section>
  );
}
